version: '3'
services:
    mongo-dump:
        build: .
        environment:
            AWS_ACCESS_KEY_ID: 'xXxXxXxXxXxXxXxX'
            AWS_REGION: 'us-xxxx-#'
            AWS_SECRET_ACCESS_KEY: 'yYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyY'
            S3_BUCKET: '<<your-bucket-name>>'
            CRON_SCHEDULE: '0 0 * * *' # every day at midnight
            MONGO_URI: 'mongodb://<<user>>:<<password>>@<<host>>:<<port>>/<<database>>'
